const { contextBridge } = require('electron');
const { ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('ecorean', {
  platform: 'electron',
  appName: 'ECOREAN BOC CEO Dashboard',
  bocDb: {
    getDashboardData: () => ipcRenderer.invoke('boc:dashboard:get'),
    decideApproval: (payload) => ipcRenderer.invoke('boc:approval:decide', payload),
    recordAction: (payload) => ipcRenderer.invoke('boc:action:record', payload),
    saveEstimateDraft: (payload) => ipcRenderer.invoke('boc:estimate-draft:save', payload),
    loadEstimateDraftForProject: (payload) => ipcRenderer.invoke('boc:estimate-draft:load', payload),
    updateEstimateDraft: (payload) => ipcRenderer.invoke('boc:estimate-draft:update', payload),
    calculateBathroomEstimate: (payload) => ipcRenderer.invoke('boc:bathroom-estimate:calculate', payload),
    saveBathroomEstimate: (payload) => ipcRenderer.invoke('boc:bathroom-estimate:save', payload),
    getProjectExecutionReadiness: (payload) => ipcRenderer.invoke('boc:execution:readiness', payload),
    transitionProjectToExecution: (payload) => ipcRenderer.invoke('boc:execution:transition', payload),
    getSiteOperationStatus: (payload) => ipcRenderer.invoke('boc:site:status', payload),
    startSiteOperation: (payload) => ipcRenderer.invoke('boc:site:start', payload),
    saveDailySiteReport: (payload) => ipcRenderer.invoke('boc:site:daily-report:save', payload),
    saveMaterialDeliveryCheck: (payload) => ipcRenderer.invoke('boc:site:material-delivery:save', payload),
    saveInspectionResult: (payload) => ipcRenderer.invoke('boc:site:inspection:save', payload),
    createSiteIssue: (payload) => ipcRenderer.invoke('boc:site:issue:create', payload),
    createChangeOrderRequest: (payload) => ipcRenderer.invoke('boc:site:change-order:create', payload),
    getProjectCompletionReadiness: (payload) => ipcRenderer.invoke('boc:completion:readiness', payload),
    completeProject: (payload) => ipcRenderer.invoke('boc:completion:complete', payload),
    getCostCaptureDashboard: () => ipcRenderer.invoke('boc:cost-capture:get'),
    saveActualCostEntry: (payload) => ipcRenderer.invoke('boc:cost-capture:save', payload),
    evaluateCostCaptureReadiness: (payload) => ipcRenderer.invoke('boc:cost-capture:evaluate', payload),
    getVendorPriceAdminData: () => ipcRenderer.invoke('boc:vendor-price:get'),
    createVendorPriceCatalogEntry: (payload) => ipcRenderer.invoke('boc:vendor-price:create', payload),
    decideVendorPriceApproval: (payload) => ipcRenderer.invoke('boc:vendor-price:decide', payload),
    getPermissionAdminData: () => ipcRenderer.invoke('boc:permissions:get'),
    getPortfolioDashboardData: () => ipcRenderer.invoke('boc:portfolio:get'),
    getCrewDashboardData: () => ipcRenderer.invoke('boc:crew:get'),
    getCompanyFinanceDashboardData: () => ipcRenderer.invoke('boc:finance:get'),
    getSalesPipelineData: () => ipcRenderer.invoke('boc:sales:get'),
    createLead: (payload) => ipcRenderer.invoke('boc:sales:lead:create', payload),
    updateLeadStatus: (payload) => ipcRenderer.invoke('boc:sales:lead:update-status', payload),
    getProfitGenerationData: () => ipcRenderer.invoke('boc:profit:get'),
    overrideProfitDecision: (payload) => ipcRenderer.invoke('boc:profit:override', payload),
    getClientContractData: () => ipcRenderer.invoke('boc:client-contract:get'),
    approveContract: (payload) => ipcRenderer.invoke('boc:client-contract:approve', payload),
    getBathroomPricingStandardDashboard: () => ipcRenderer.invoke('boc:bathroom-pricing:get'),
    evaluateBathroomQuote: (payload) => ipcRenderer.invoke('boc:bathroom-pricing:evaluate', payload),
    getCaseLibrarySnapshot: () => ipcRenderer.invoke('boc:case-library:get'),
    runCaseLearningAnalysis: (payload) => ipcRenderer.invoke('boc:case-library:analyze', payload),
    getBackupStatus: () => ipcRenderer.invoke('boc:backup:status'),
    createFullBackup: (payload) => ipcRenderer.invoke('boc:backup:full', payload),
    createDatabaseBackup: (payload) => ipcRenderer.invoke('boc:backup:database', payload),
    previewRestore: (payload) => ipcRenderer.invoke('boc:backup:restore-preview', payload),
    restoreBackup: (payload) => ipcRenderer.invoke('boc:backup:restore', payload),
    exportJson: (payload) => ipcRenderer.invoke('boc:export:json', payload),
    exportExcel: (payload) => ipcRenderer.invoke('boc:export:excel', payload),
    getStats: () => ipcRenderer.invoke('boc:db:stats')
  }
});
