import type { DashboardData } from './dashboard';

type ApprovalDecisionPayload = {
  approvalId: string;
  decision: 'APPROVED' | 'REJECTED' | 'REVISION_REQUESTED';
  actor?: string;
  reasonKo?: string;
};

type ActionRecordPayload = {
  actionType: 'BLOCK' | 'ORDER' | 'CLAIM' | 'APPROVED' | 'REJECTED' | 'REVISION_REQUESTED' | 'SAVE_ESTIMATE_DRAFT' | 'UPDATE_ESTIMATE_DRAFT' | 'CAPTURE_ACTUAL_COST' | 'CREATE_VENDOR_PRICE_PENDING' | 'VENDOR_PRICE_APPROVED' | 'VENDOR_PRICE_REJECTED' | 'VENDOR_PRICE_REQUEST_REVISION';
  actor?: string;
  projectId?: string;
  approvalId?: string | null;
  reasonKo?: string;
  payload?: Record<string, unknown>;
};

declare global {
  interface Window {
    ecorean?: {
      platform: string;
      appName: string;
      bocDb?: {
        getDashboardData: () => Promise<DashboardData>;
        decideApproval: (payload: ApprovalDecisionPayload) => Promise<DashboardData>;
        recordAction: (payload: ActionRecordPayload) => Promise<DashboardData>;
        saveEstimateDraft: (payload: Record<string, unknown>) => Promise<{ dashboardData: DashboardData; savedDraft: Record<string, unknown> }>;
        loadEstimateDraftForProject: (payload: Record<string, unknown>) => Promise<Record<string, unknown> | null>;
        updateEstimateDraft: (payload: Record<string, unknown>) => Promise<{ dashboardData: DashboardData; savedDraft: Record<string, unknown> }>;
        calculateBathroomEstimate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveBathroomEstimate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        exportBathroomEstimate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        calculateKitchenEstimate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveKitchenEstimate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        exportKitchenEstimate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        calculateFullRemodelingEstimate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveFullRemodelingEstimate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        exportFullRemodelingEstimate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getAiEstimateIntelligence: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        decideAiRecommendationAction: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generateBathroomContract: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        exportBathroomContractPdf: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generateBathroomSchedule: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generateBathroomPurchaseOrder: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generateKitchenContract: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generateKitchenSchedule: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generateKitchenPurchaseOrder: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generateFullRemodelingContract: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generateFullRemodelingSchedule: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generateFullRemodelingPurchaseOrder: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getFloorplanCenterData: (payload?: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveFloorplanMetadata: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createFloorplanSpace: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        linkEstimateItemToSpace: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveMoodboardProfile: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generatePerspectivePrompt: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getAIVisualizationCenterData: (payload?: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createVisualizationBrief: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        generateVisualizationPrompts: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        queueVisualizationJob: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getComfyUiSettingsData: () => Promise<Record<string, unknown>>;
        saveComfyUiSettings: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        checkComfyUiHealth: () => Promise<Record<string, unknown>>;
        saveComfyUiWorkflowPreset: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        runComfyUiGeneration: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        refreshComfyUiJobStatus: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        attachVisualizationResult: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        decideVisualizationResult: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getBoardGenerationCenterData: (payload?: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createDesignBoard: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        exportDesignBoardPdf: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createPortfolioCandidate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getProjectExecutionReadiness: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getFieldMobileCenterData: (payload?: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveFieldAttendanceCheckIn: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveFieldAttendanceCheckOut: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createFieldDailyReport: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveSiteMediaFile: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createFieldMaterialReceiving: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveFieldInspectionResult: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createFieldChangeOrderRequest: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createFieldDefectReport: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveFieldSignature: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createFieldRiskReport: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        transitionProjectToExecution: (payload: Record<string, unknown>) => Promise<{ dashboardData: DashboardData; executionProject: Record<string, unknown> }>;
        getSiteOperationStatus: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        startSiteOperation: (payload: Record<string, unknown>) => Promise<{ dashboardData: DashboardData; siteOperation: Record<string, unknown> }>;
        saveDailySiteReport: (payload: Record<string, unknown>) => Promise<{ dashboardData: DashboardData; reportId: string }>;
        saveMaterialDeliveryCheck: (payload: Record<string, unknown>) => Promise<{ dashboardData: DashboardData; deliveryCheckId: string }>;
        saveInspectionResult: (payload: Record<string, unknown>) => Promise<{ dashboardData: DashboardData; inspectionResultId: string; blockedProcesses: string[] }>;
        createSiteIssue: (payload: Record<string, unknown>) => Promise<{ dashboardData: DashboardData; siteIssueId: string }>;
        createChangeOrderRequest: (payload: Record<string, unknown>) => Promise<{ dashboardData: DashboardData; changeOrderId: string }>;
        createDailySiteReportFromSchedule: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createCrewAttendanceReport: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createMaterialReceivingLog: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createInspectionChecklistFromSchedule: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveInspectionChecklistResults: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createExecutionChangeOrder: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        approveExecutionChangeOrder: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createDefectReport: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getProjectCompletionReadiness: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        completeProject: (payload: Record<string, unknown>) => Promise<{ dashboardData: DashboardData; completionReport: Record<string, unknown> }>;
        getCostCaptureDashboard: () => Promise<Record<string, unknown>>;
        saveActualCostEntry: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        evaluateCostCaptureReadiness: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getVendorPriceAdminData: () => Promise<Record<string, unknown>>;
        createVendorPriceCatalogEntry: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        decideVendorPriceApproval: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getVendorPriceIntelligenceData: () => Promise<Record<string, unknown>>;
        saveMaterialPriceHistory: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        importMaterialPriceHistoryCsv: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        decideVendorPriceRecommendation: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getVendorSelectionRecommendation: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getMasterDataCenterData: (payload?: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createMasterDataItem: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        runMasterDataValidation: (payload?: Record<string, unknown>) => Promise<Record<string, unknown>>;
        importMasterDataCsv: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        exportMasterDataCsv: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getFranchiseCenterData: (payload?: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createFranchiseBranch: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        publishFranchiseDistributionPackage: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        applyFranchisePackageToBranch: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createBranchProfitPolicy: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        calculateFranchiseFeeRecord: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        markFranchiseFeePaid: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createFranchiseReplicationTemplate: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        applyReplicationTemplateToBranch: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getPermissionAdminData: () => Promise<Record<string, unknown>>;
        getPortfolioDashboardData: () => Promise<Record<string, unknown>>;
        getCrewDashboardData: () => Promise<Record<string, unknown>>;
        getCompanyFinanceDashboardData: () => Promise<Record<string, unknown>>;
        getSalesPipelineData: () => Promise<Record<string, unknown>>;
        createLead: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        updateLeadStatus: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getProfitGenerationData: () => Promise<Record<string, unknown>>;
        overrideProfitDecision: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getCeoControlTowerData: () => Promise<Record<string, unknown>>;
        decideCeoApprovalRequest: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getClientContractData: () => Promise<Record<string, unknown>>;
        approveContract: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getCommunicationCenterData: () => Promise<Record<string, unknown>>;
        generateCommunicationMessage: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        markCommunicationMessageSent: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        cancelCommunicationMessage: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getPaymentCenterData: () => Promise<Record<string, unknown>>;
        markCustomerPaymentReceived: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        markVendorPaymentPaid: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createPaymentRequestMessage: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        requestVendorPaymentApproval: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getProjectClosingCenterData: (payload?: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createProjectClosingSnapshot: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        finalizeProjectClosing: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        saveHighMarginTemplateFromClosing: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getProjectCalibrationCenterData: (payload?: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createProjectCalibrationSnapshot: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        decideCalibrationRule: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getBathroomPricingStandardDashboard: () => Promise<Record<string, unknown>>;
        evaluateBathroomQuote: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getCaseLibrarySnapshot: () => Promise<Record<string, unknown>>;
        runCaseLearningAnalysis: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getBackupStatus: () => Promise<Record<string, unknown>>;
        createFullBackup: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        createDatabaseBackup: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        previewRestore: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        restoreBackup: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        exportJson: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        exportExcel: (payload: Record<string, unknown>) => Promise<Record<string, unknown>>;
        getStats: () => Promise<Record<string, unknown>>;
      };
    };
  }
}

export {};
